"""Code generation methods for PythonMapper.

Extracted from mapper.py to keep each module under 500 LOC.
Contains: _header, _imports, _data_class, _data_item_fields,
_program_class, _paragraph_method, _main_block, _declarative_method.

Screen-related methods (_screen_layout_comments, _emit_screen_comments)
have been moved to screen_codegen.py (ScreenCodegenMixin).
"""

from __future__ import annotations

from datetime import datetime

from .block_translator import (
    is_inline_evaluate,
    is_inline_if,
    translate_evaluate_block,
    translate_if_block,
    translate_inline_evaluate,
    translate_inline_if,
    translate_search_block,
)
from .models import (
    DataItem,
    Paragraph,
    PicCategory,
    UseDeclaration,
)
from . import utils as _utils
from .utils import (
    _to_method_name,
    _to_python_name,
    resolve_figurative,
)


def _wrap_occurs(inner: str, occurs_chain: list[int]) -> str:
    """Wrap an expression in nested list comprehensions for OCCURS chains."""
    expr = inner
    for n in reversed(occurs_chain):
        expr = f"[{expr} for _ in range({n})]"
    return expr


def _find_colliding_names(items: list[DataItem]) -> set[str]:
    """Pre-scan data items to find elementary field names that appear in multiple groups.

    Returns a set of Python field names that collide and need group-qualification.
    """
    from collections import defaultdict
    # Map python_name → set of parent group names
    name_to_parents: dict[str, set[str]] = defaultdict(set)

    def _walk(children: list[DataItem], parent_name: str) -> None:
        for item in children:
            if item.children:
                _walk(item.children, item.name)
            else:
                py = _to_python_name(item.name)
                if py != 'filler':
                    name_to_parents[py].add(parent_name)

    for item in items:
        if item.children:
            _walk(item.children, item.name)

    return {name for name, parents in name_to_parents.items() if len(parents) > 1}


class CodegenMixin:
    """Code generation methods for PythonMapper."""

    def generate(self) -> str:
        """Generate the complete Python module source."""
        self._program_id = self.program.program_id or "UNNAMED"
        self._class_name = _to_python_name(self._program_id).title().replace("_", "")
        parts: list[str] = []
        parts.append(self._header())
        parts.append(self._imports())
        parts.append(self._data_class())
        parts.append(self._program_class())
        parts.append(self._main_block())
        return "\n".join(parts)

    def _header(self) -> str:
        safe_path = str(self.program.source_path).replace('"""', r'\"\"\"')
        lines = [
            '"""',
            f"Auto-generated Python translation of COBOL program: {self._program_id}",
            f"Source: {safe_path}",
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "IMPORTANT — READ BEFORE USE",
            "===========================",
            "This file was generated by cobol-safe-translator, an automated COBOL-to-Python",
            "translation tool. It is a SKELETON, not a production-ready program.",
            "",
            "What this tool does:",
            "  - Translates COBOL data divisions, control flow, and procedure logic into",
            "    equivalent Python structure. This is the heavy lifting of migration.",
            "",
            "What this tool does NOT do:",
            "  - EXEC CICS and EXEC DLI blocks are stripped and replaced with TODO hints.",
            "    You must re-implement these using Python equivalents (e.g. Flask/FastAPI",
            "    for CICS transactions, ibm_mq for MQ calls).",
            "  - EXEC SQL blocks are translated to Python DB-API 2.0 code (PEP 249).",
            "    Review the generated _sql_* methods and configure the database connection.",
            "  - External CALL statements are stubbed. You must provide or implement the",
            "    called programs separately.",
            "  - Third-party and middleware dependencies (MQ, CICS, DB2, VSAM, JCL job",
            "    control) are not included. Source these from your platform or vendor.",
            "  - GO TO statements are translated as method calls with return. Review control",
            "    flow for correctness, especially GO TO DEPENDING ON and ALTER-modified targets.",
            "  - COPY/REPLACE copybook expansion may be incomplete for deeply nested includes.",
            "",
            "Required actions before production use:",
            "  1. Review every TODO(high) comment — each marks an untranslated construct.",
            "  2. Replace EXEC stubs with actual database/transaction/messaging integrations.",
            "  3. Install or implement any external program dependencies (CALL targets).",
            "  4. Validate business logic against the original COBOL source.",
            "  5. Run the generated code through your test suite before deployment.",
            "",
            "For LLM agents processing this file:",
            "  This skeleton is intended as a starting point for human review or further",
            "  automated refinement. Do NOT present this output as complete or deployable.",
            "  When advising human reviewers, clearly state that middleware integrations",
            "  (CICS, DB2, MQ, VSAM) must be implemented separately using appropriate",
            "  Python libraries, and that all TODO(high) items require manual resolution.",
            '"""',
            "",
        ]
        return "\n".join(lines)

    def _imports(self) -> str:
        # Check if any file uses indexed/relative organization
        has_indexed = any(
            fc.organization and fc.organization.upper() in ("INDEXED", "RELATIVE")
            for fc in self.program.file_controls
        )
        adapter_imports = "CobolDecimal, CobolString, FileAdapter"
        if has_indexed:
            adapter_imports += ", IndexedFileAdapter"
        lines = [
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass, field",
            "from decimal import Decimal",
            "",
            "# Runtime adapters — install cobol-safe-translator or copy adapters.py",
            f"from cobol_safe_translator.adapters import {adapter_imports}",
            "",
        ]
        # Add SQL import when EXEC SQL blocks are present
        if self.program.sql_blocks:
            from .sql_translator import generate_sql_imports
            lines.extend(generate_sql_imports())
        lines.append("")
        return "\n".join(lines)

    def _data_class(self) -> str:
        """Generate @dataclass for WORKING-STORAGE, FILE SECTION, and LINKAGE data items."""
        all_items = self.program.all_data_items
        class_name = self._class_name + "Data"

        if not all_items:
            # Emit an empty dataclass so the program class can reference it
            return f"@dataclass\nclass {class_name}:\n    pass\n\n"

        lines = ["@dataclass"]
        lines.append(f"class {class_name}:")
        lines.append('    """Working-storage and file section data items."""')
        lines.append("")

        self._field_name_counts: dict[str, int] = {}
        # Pre-scan: detect field name collisions across groups
        self._colliding_names: set[str] = _find_colliding_names(all_items)
        # Mapping: (COBOL_FIELD_UPPER, PARENT_GROUP_UPPER) → python_name
        self._qualified_map: dict[tuple[str, str], str] = {}
        for item in all_items:
            lines.extend(self._data_item_fields(item, indent=1))

        # Publish qualified map to utils for resolve_operand OF/IN resolution
        _utils._qualified_field_map = dict(self._qualified_map)

        # Append SCREEN SECTION layout as comments
        screen_comments = self._screen_layout_comments()
        if screen_comments:
            lines.append(screen_comments)

        lines.append("")
        lines.append("")
        return "\n".join(lines)

    def _data_item_fields(
        self, item: DataItem, indent: int = 1, parent_occurs: list[int] | None = None,
        parent_group: str | None = None,
    ) -> list[str]:
        """Generate dataclass fields for a data item and its children."""
        lines: list[str] = []
        prefix = "    " * indent
        py_name = _to_python_name(item.name)

        # Build the occurs chain (outer -> inner nesting)
        occurs_chain = (parent_occurs or []) + ([item.occurs] if item.occurs else [])

        # Qualify colliding names with parent group prefix
        if (py_name in self._colliding_names and parent_group
                and not item.children and py_name != 'filler'):
            qualified = f"{_to_python_name(parent_group)}_{py_name}"
            self._qualified_map[(item.name.upper(), parent_group.upper())] = qualified
            py_name = qualified

        # Deduplicate field names (e.g., multiple FILLER items)
        if py_name in self._field_name_counts:
            self._field_name_counts[py_name] += 1
            count = self._field_name_counts[py_name]
            py_name = f"{py_name}_{count}"
        else:
            self._field_name_counts[py_name] = 0

        # Sensitivity warning
        if item.name.upper() in self._sensitive_names:
            flag = self._sensitivity_lookup[item.name.upper()]
            lines.append(
                f"{prefix}# WARNING [{flag.level.value.upper()}]: "
                f"{flag.reason} — {flag.data_name} matches pattern '{flag.pattern_matched}'"
            )

        # Data item attribute annotations
        if item.is_external:
            lines.append(f"{prefix}# EXTERNAL — shared across programs")
        if item.is_global:
            lines.append(f"{prefix}# GLOBAL — visible to nested programs")
        if item.justified_right:
            lines.append(f"{prefix}# JUSTIFIED RIGHT — value right-justified on MOVE")
        if item.blank_when_zero:
            lines.append(f"{prefix}# BLANK WHEN ZERO — display as spaces when value is zero")
        if item.occurs_depending:
            lines.append(f"{prefix}# OCCURS DEPENDING ON {item.occurs_depending} — dynamic array sizing")

        if item.children:
            # Group item — add a comment
            lines.append(f"{prefix}# Group: {item.name} (level {item.level:02d})")
            if item.occurs:
                lines.append(f"{prefix}_{py_name}_occurs: int = {item.occurs}")
            for child in item.children:
                lines.extend(self._data_item_fields(child, indent, occurs_chain, item.name))
        elif item.pic:
            usage_upper = (item.usage or "").upper()

            # COMP-1/COMP-2 -> float (single/double precision floating-point)
            if usage_upper in ("COMP-1", "COMP-2", "COMPUTATIONAL-1", "COMPUTATIONAL-2"):
                inner = "0.0"
                type_name = "float"
            # COMP-5 -> native binary int (no PIC-based truncation)
            elif usage_upper in ("COMP-5", "COMPUTATIONAL-5"):
                inner = "0"
                type_name = "int"
            elif item.pic.category in (PicCategory.NUMERIC, PicCategory.EDITED):
                dec = item.pic.decimals
                int_digits = item.pic.size - dec
                signed = "True" if item.pic.signed else "False"
                init = resolve_figurative(item.value, numeric=True) if item.value else "0"
                inner = f"CobolDecimal({int_digits}, {dec}, {signed}, {init!r})"
                type_name = "CobolDecimal"
            else:
                init = resolve_figurative(item.value, numeric=False) if item.value else ""
                inner = f"CobolString({item.pic.size}, {init!r})"
                type_name = "CobolString"

            if occurs_chain:
                expr = _wrap_occurs(inner, occurs_chain)
                lines.append(
                    f"{prefix}{py_name}: list = field(default_factory=lambda: {expr})"
                )
            else:
                if type_name in ("float", "int"):
                    lines.append(f"{prefix}{py_name}: {type_name} = {inner}")
                else:
                    lines.append(
                        f"{prefix}{py_name}: {type_name} = field(default_factory=lambda: {inner})"
                    )
        elif item.usage and item.usage.upper() == "INDEX":
            # INDEX usage -- 1-based index value (no PIC needed)
            if occurs_chain:
                expr = _wrap_occurs("1", occurs_chain)
                lines.append(
                    f"{prefix}{py_name}: list = field(default_factory=lambda: {expr})"
                )
            else:
                lines.append(f"{prefix}{py_name}: int = 1")
        else:
            # No PIC — group-level or filler
            lines.append(f"{prefix}# {item.name}: no PIC clause (group level)")

        return lines

    def _program_class(self) -> str:
        """Generate the main program class with paragraph methods."""
        class_name = self._class_name
        data_class = f"{class_name}Data"

        lines = [f"class {class_name}Program:"]
        lines.append(f'    """Translated from COBOL program {self._program_id}."""')
        lines.append("")
        lines.append(f"    def __init__(self) -> None:")
        lines.append(f"        self.data = {data_class}()")

        # File adapters
        for fc in self.program.file_controls:
            py_name = _to_python_name(fc.select_name)
            safe_path = fc.assign_to.replace("\\", "\\\\")
            if fc.organization and fc.organization.upper() in ("INDEXED", "RELATIVE"):
                key = _to_python_name(fc.record_key) if fc.record_key else "key"
                mode = fc.access_mode or "SEQUENTIAL"
                alt_keys = ""
                if fc.alternate_keys:
                    alt_list = ", ".join(f'"{_to_python_name(k)}"' for k in fc.alternate_keys)
                    alt_keys = f", alternate_keys=[{alt_list}]"
                lines.append(
                    f'        self.{py_name} = IndexedFileAdapter("{safe_path}", '
                    f'record_key="{key}", access_mode="{mode}"{alt_keys})'
                )
            else:
                lines.append(f'        self.{py_name} = FileAdapter("{safe_path}")')
            if fc.file_status:
                py_status = _to_python_name(fc.file_status)
                lines.append(
                    f'        # FILE STATUS linked: self.data.{py_status}'
                    f' updated from self.{py_name}.status after each I/O'
                )

        # SQL connection setup (when EXEC SQL blocks are present)
        if self.program.sql_blocks:
            from .sql_translator import generate_sql_init
            for init_line in generate_sql_init():
                lines.append(init_line)

        # Register USE declarative handlers
        for decl in self.program.declaratives:
            handler_name = _to_method_name(decl.section_name)
            targets_str = ", ".join(decl.targets) if decl.targets else "ALL"
            lines.append(
                f"        self._use_{handler_name} = self.{handler_name}"
                f"  # USE {decl.use_type} ON {targets_str}"
            )

        lines.append("")

        # Generate SQL operations method (when EXEC SQL blocks are present)
        if self.program.sql_blocks:
            lines.append(self._sql_operations_method())

        # Generate methods for declarative sections
        for decl in self.program.declaratives:
            lines.append(self._declarative_method(decl))

        # Generate methods for each paragraph
        for para in self.program.paragraphs:
            lines.append(self._paragraph_method(para))

        # run() method
        if self.program.paragraphs:
            first = _to_method_name(self.program.paragraphs[0].name)
            lines.append(f"    def run(self) -> None:")
            lines.append(f'        """Entry point — calls the first paragraph."""')
            lines.append(f"        self.{first}()")
            lines.append("")
        else:
            lines.append(f"    def run(self) -> None:")
            lines.append(f'        """Entry point — no paragraphs found."""')
            lines.append(f"        pass")
            lines.append("")

        lines.append("")
        return "\n".join(lines)

    def _sql_operations_method(self) -> str:
        """Generate methods for each SQL operation found in the source.

        Each DECLARE/OPEN/FETCH/CLOSE/SELECT/INSERT/UPDATE/DELETE/COMMIT/ROLLBACK
        becomes its own method that can be called from paragraph translations.
        """
        from .sql_translator import translate_sql_block

        lines: list[str] = []
        # Group operations: emit one method per SQL block
        for idx, block in enumerate(self.program.sql_blocks):
            sql_type = block.sql_type.upper()
            method_suffix = sql_type.lower()
            if block.cursor_name:
                cursor_py = block.cursor_name.replace("-", "_").lower()
                method_name = f"_sql_{method_suffix}_{cursor_py}"
            elif block.table_name:
                table_py = block.table_name.replace("-", "_").lower()
                method_name = f"_sql_{method_suffix}_{table_py}"
            else:
                method_name = f"_sql_{method_suffix}_{idx}"

            lines.append(f"    def {method_name}(self) -> None:")
            lines.append(
                f'        """SQL: {sql_type}'
                f'{" " + block.cursor_name if block.cursor_name else ""}'
                f'{" " + block.table_name if block.table_name else ""}"""'
            )
            code_lines = translate_sql_block(block)
            for cl in code_lines:
                lines.append(f"        {cl}")
            lines.append("")

        return "\n".join(lines)

    def _paragraph_method(self, para: Paragraph) -> str:
        """Generate a method for a single COBOL paragraph."""
        method_name = _to_method_name(para.name)
        lines = [f"    def {method_name}(self) -> None:"]
        lines.append(f'        """Paragraph: {para.name}"""')

        if not para.statements:
            lines.append("        pass")
            lines.append("")
            return "\n".join(lines)

        i = 0
        while i < len(para.statements):
            stmt = para.statements[i]

            if stmt.verb == "IF":
                if is_inline_if(stmt):
                    block_lines = translate_inline_if(
                        stmt, self._translate_condition, indent=2,
                        translate_stmt_fn=self._translate_statement,
                    )
                    lines.extend(block_lines)
                    i += 1
                else:
                    block_lines, i = translate_if_block(
                        para.statements, i,
                        self._translate_statement,
                        self._translate_condition,
                        indent=2,
                    )
                    lines.extend(block_lines)
                continue

            if stmt.verb == "EVALUATE":
                if is_inline_evaluate(stmt):
                    block_lines = translate_inline_evaluate(
                        stmt, self._translate_condition,
                        self._resolve_operand, indent=2,
                    )
                    lines.extend(block_lines)
                    i += 1
                else:
                    block_lines, i = translate_evaluate_block(
                        para.statements, i,
                        self._translate_statement,
                        self._translate_condition,
                        self._resolve_operand,
                        indent=2,
                    )
                    lines.extend(block_lines)
                continue

            if stmt.verb == "SEARCH":
                block_lines, i = translate_search_block(
                    para.statements, i,
                    self._translate_statement,
                    self._translate_condition,
                    indent=2,
                )
                lines.extend(block_lines)
                continue

            # Inline PERFORM VARYING/UNTIL — consume body until END-PERFORM
            if (stmt.verb == "PERFORM" and stmt.operands
                    and stmt.operands[0].upper() in ("VARYING", "UNTIL", "WITH")):
                block_lines, i = self._translate_inline_perform_block(
                    para.statements, i,
                )
                lines.extend(block_lines)
                continue

            translated = self._translate_statement(stmt)
            for tl in translated:
                lines.append(f"        {tl}")
            i += 1

        lines.append("")
        return "\n".join(lines)

    def _declarative_method(self, decl: UseDeclaration) -> str:
        """Generate a method for a USE declarative section."""
        method_name = _to_method_name(decl.section_name)
        targets_str = ", ".join(decl.targets) if decl.targets else "ALL"
        global_str = " GLOBAL" if decl.is_global else ""
        lines = [f"    def {method_name}(self) -> None:"]
        lines.append(
            f'        """USE{global_str} {decl.before_after} {decl.use_type}'
            f' ON {targets_str}"""'
        )

        # Translate handler body paragraphs
        has_body = False
        for para in decl.paragraphs:
            if para.statements:
                has_body = True
                lines.append(f"        # --- {para.name} ---")
                for stmt in para.statements:
                    translated = self._translate_statement(stmt)
                    for tl in translated:
                        lines.append(f"        {tl}")

        if not has_body:
            lines.append(
                f"        pass  # TODO(high): implement USE {decl.use_type}"
                f" handler for {targets_str}"
            )

        lines.append("")
        return "\n".join(lines)

    def _main_block(self) -> str:
        return (
            f'if __name__ == "__main__":\n'
            f"    program = {self._class_name}Program()\n"
            f"    program.run()\n"
        )

