"""Generate middleware interface stubs for translated COBOL projects.

When a COBOL project uses DB2/CICS/DLI/MQ, the translator emits TODO markers.
This module generates typed interface stubs so multiple developers can work
against defined contracts before the middleware is wired up.

Pipeline: ProjectMap -> detect middleware usage -> generate stub files
"""

from __future__ import annotations

from pathlib import Path

from .models import ProjectMap, SoftwareMap


# --- Detection ---

def _detect_middleware(smap: SoftwareMap) -> dict[str, bool]:
    """Detect which middleware a single program uses."""
    program = smap.program
    return {
        "db2": bool(program.sql_blocks),
        "cics": any(
            "CICS" in s.verb.upper()
            for p in program.paragraphs
            for s in p.statements
        ),
        "dli": bool(program.dli_blocks),
        "mq": any(
            "MQPUT" in s.raw_text.upper() or "MQGET" in s.raw_text.upper()
            or "MQOPEN" in s.raw_text.upper() or "MQCLOSE" in s.raw_text.upper()
            for p in program.paragraphs
            for s in p.statements
        ),
    }


def detect_project_middleware(project_map: ProjectMap) -> dict[str, bool]:
    """Detect middleware usage across all programs in a project."""
    combined = {"db2": False, "cics": False, "dli": False, "mq": False}
    for smap in project_map.programs.values():
        per_prog = _detect_middleware(smap)
        for k in combined:
            combined[k] = combined[k] or per_prog[k]
    return combined


# --- Stub templates ---

_DB2_STUB = '''\
"""DB2 database interface stub.

Generated by cobol-safe-translator. Implement these methods to connect
your translated COBOL programs to your database.

Usage:
    from .db2_interface import DB2Connection
    db = DB2Connection()
    db.connect("DSN=MYDB")
"""

from __future__ import annotations

from typing import Any


class DB2Connection:
    """DB-API 2.0 compatible database interface.

    The translated programs call cursor.execute() and cursor.fetchone().
    Implement this class to connect to your actual database (PostgreSQL,
    MySQL, SQLite, etc.).
    """

    def __init__(self) -> None:
        self._connection: Any = None
        self._cursor: Any = None
        self.sqlcode: int = 0

    def connect(self, dsn: str, **kwargs: Any) -> None:
        """Connect to the database.

        Replace with your actual connection logic:
            import psycopg2
            self._connection = psycopg2.connect(dsn)
            self._cursor = self._connection.cursor()
        """
        raise NotImplementedError("Wire up your database connection here")

    def cursor(self) -> Any:
        """Return a DB-API 2.0 cursor."""
        if self._cursor is None:
            raise RuntimeError("Not connected — call connect() first")
        return self._cursor

    def execute(self, sql: str, params: tuple[Any, ...] = ()) -> None:
        """Execute a SQL statement with parameterized values."""
        try:
            self.cursor().execute(sql, params)
            self.sqlcode = 0
        except Exception as exc:
            self.sqlcode = -1
            raise

    def fetchone(self) -> tuple[Any, ...] | None:
        """Fetch one row from the last query."""
        row = self.cursor().fetchone()
        if row is None:
            self.sqlcode = 100  # NOT FOUND
        return row

    def fetchall(self) -> list[tuple[Any, ...]]:
        """Fetch all rows from the last query."""
        return self.cursor().fetchall()

    def commit(self) -> None:
        """Commit the current transaction."""
        if self._connection:
            self._connection.commit()

    def rollback(self) -> None:
        """Roll back the current transaction."""
        if self._connection:
            self._connection.rollback()

    def close(self) -> None:
        """Close the connection."""
        if self._cursor:
            self._cursor.close()
        if self._connection:
            self._connection.close()
'''

_CICS_STUB = '''\
"""CICS transaction interface stub.

Generated by cobol-safe-translator. Implement these methods to connect
your translated COBOL programs to your web/transaction framework.

Usage:
    from .cics_interface import CICSRuntime
    cics = CICSRuntime()
    cics.send_map("MENU01", {"ACCT-NUM": "12345"})
"""

from __future__ import annotations

from typing import Any


class CICSRuntime:
    """CICS transaction runtime interface.

    The translated programs call methods like send_map(), receive_map(),
    link(), and xctl(). Implement this class using Flask, FastAPI,
    or your transaction framework.
    """

    def __init__(self) -> None:
        self.eibtrnid: str = ""
        self.eibcalen: int = 0
        self.commarea: dict[str, Any] = {}
        self.resp: int = 0
        self.resp2: int = 0

    def send_map(self, mapname: str, data: dict[str, Any] | None = None) -> None:
        """Send a BMS map to the terminal (display a screen).

        Replace with your web framework:
            return render_template(f"{mapname}.html", **data)
        """
        raise NotImplementedError(f"Implement screen rendering for map {mapname}")

    def receive_map(self, mapname: str) -> dict[str, Any]:
        """Receive input from a BMS map (read user input).

        Replace with your web framework:
            return request.form.to_dict()
        """
        raise NotImplementedError(f"Implement input handling for map {mapname}")

    def link(self, program: str, commarea: dict[str, Any] | None = None) -> None:
        """LINK to another program (call and return).

        Replace with:
            from . import target_program
            target_program.run(commarea)
        """
        raise NotImplementedError(f"Implement LINK to program {program}")

    def xctl(self, program: str, commarea: dict[str, Any] | None = None) -> None:
        """XCTL to another program (transfer control, no return).

        Replace with:
            from . import target_program
            target_program.run(commarea)
            raise SystemExit(0)  # no return
        """
        raise NotImplementedError(f"Implement XCTL to program {program}")

    def return_transid(self, transid: str, commarea: dict[str, Any] | None = None) -> None:
        """RETURN with TRANSID (end transaction, set next).

        Replace with session management:
            session["next_transid"] = transid
            session["commarea"] = commarea
        """
        raise NotImplementedError(f"Implement RETURN TRANSID {transid}")

    def read_file(self, filename: str, key: str) -> dict[str, Any]:
        """READ a VSAM file (CICS FILE CONTROL).

        Replace with database or file lookup.
        """
        raise NotImplementedError(f"Implement CICS READ for file {filename}")

    def write_file(self, filename: str, record: dict[str, Any]) -> None:
        """WRITE to a VSAM file (CICS FILE CONTROL)."""
        raise NotImplementedError(f"Implement CICS WRITE for file {filename}")
'''

_DLI_STUB = '''\
"""DLI/IMS database interface stub.

Generated by cobol-safe-translator. Implement these methods to connect
your translated COBOL programs to your hierarchical database or API.

Usage:
    from .dli_interface import DLIConnection
    dli = DLIConnection()
    segment = dli.get_unique("CUSTOMER", ssa=["CUSTNO = 12345"])
"""

from __future__ import annotations

from typing import Any


class DLIConnection:
    """DLI/IMS hierarchical database interface.

    The translated programs call GU, GN, ISRT, REPL, DLET operations.
    Implement this class to connect to your actual data store.
    """

    def __init__(self) -> None:
        self.status_code: str = "  "  # 2-char DLI status (spaces = OK)
        self._pcb_status: dict[str, str] = {}

    def get_unique(self, segment: str, ssa: list[str] | None = None,
                   pcb: str = "") -> dict[str, Any] | None:
        """GU — Get Unique. Direct retrieval by SSA qualification.

        Replace with your database query:
            return db.query(segment).filter(ssa).first()
        """
        raise NotImplementedError(f"Implement GU for segment {segment}")

    def get_next(self, segment: str, ssa: list[str] | None = None,
                 pcb: str = "") -> dict[str, Any] | None:
        """GN — Get Next. Sequential retrieval.

        Replace with your database cursor:
            return db.query(segment).next()
        """
        raise NotImplementedError(f"Implement GN for segment {segment}")

    def get_next_within_parent(self, segment: str, ssa: list[str] | None = None,
                               pcb: str = "") -> dict[str, Any] | None:
        """GNP — Get Next within Parent. Sequential under current parent."""
        raise NotImplementedError(f"Implement GNP for segment {segment}")

    def insert(self, segment: str, data: dict[str, Any],
               ssa: list[str] | None = None, pcb: str = "") -> None:
        """ISRT — Insert a new segment occurrence."""
        raise NotImplementedError(f"Implement ISRT for segment {segment}")

    def replace(self, segment: str, data: dict[str, Any],
                pcb: str = "") -> None:
        """REPL — Replace the last retrieved segment."""
        raise NotImplementedError(f"Implement REPL for segment {segment}")

    def delete(self, segment: str, pcb: str = "") -> None:
        """DLET — Delete the last retrieved segment."""
        raise NotImplementedError(f"Implement DLET for segment {segment}")

    def get_hold_unique(self, segment: str, ssa: list[str] | None = None,
                        pcb: str = "") -> dict[str, Any] | None:
        """GHU — Get Hold Unique (lock for update)."""
        return self.get_unique(segment, ssa, pcb)

    def get_hold_next(self, segment: str, ssa: list[str] | None = None,
                      pcb: str = "") -> dict[str, Any] | None:
        """GHN — Get Hold Next (lock for update)."""
        return self.get_next(segment, ssa, pcb)
'''

_MQ_STUB = '''\
"""MQ message queue interface stub.

Generated by cobol-safe-translator. Implement these methods to connect
your translated COBOL programs to your message broker.

Usage:
    from .mq_interface import MQConnection
    mq = MQConnection()
    mq.connect("QM1")
    mq.put("REQUEST.QUEUE", b"message data")
"""

from __future__ import annotations

from typing import Any


class MQConnection:
    """IBM MQ compatible message queue interface.

    Implement this class using your message broker:
    - ibm_mq (IBM MQ client)
    - pika (RabbitMQ)
    - confluent_kafka (Kafka)
    - boto3 (AWS SQS)
    """

    def __init__(self) -> None:
        self._connection: Any = None
        self.completion_code: int = 0
        self.reason_code: int = 0

    def connect(self, queue_manager: str, **kwargs: Any) -> None:
        """Connect to the queue manager.

        Replace with:
            import pymqi
            self._connection = pymqi.connect(queue_manager)
        """
        raise NotImplementedError(f"Implement connection to {queue_manager}")

    def put(self, queue_name: str, message: bytes,
            correlation_id: bytes = b"") -> None:
        """MQPUT — Put a message on a queue."""
        raise NotImplementedError(f"Implement MQPUT for queue {queue_name}")

    def get(self, queue_name: str, wait_interval: int = 0,
            correlation_id: bytes = b"") -> bytes | None:
        """MQGET — Get a message from a queue."""
        raise NotImplementedError(f"Implement MQGET for queue {queue_name}")

    def open_queue(self, queue_name: str, mode: str = "INPUT") -> None:
        """MQOPEN — Open a queue for input or output."""
        raise NotImplementedError(f"Implement MQOPEN for queue {queue_name}")

    def close_queue(self, queue_name: str) -> None:
        """MQCLOSE — Close a queue."""
        raise NotImplementedError(f"Implement MQCLOSE for queue {queue_name}")

    def disconnect(self) -> None:
        """Disconnect from the queue manager."""
        if self._connection:
            self._connection = None
'''


# --- Generator ---

def generate_stubs(
    project_map: ProjectMap,
    output_dir: Path,
) -> list[Path]:
    """Generate middleware interface stubs based on detected usage.

    Only generates stubs for middleware actually used by the project.
    Returns list of written file paths.
    """
    usage = detect_project_middleware(project_map)
    written: list[Path] = []
    output_dir.mkdir(parents=True, exist_ok=True)

    if usage["db2"]:
        p = output_dir / "db2_interface.py"
        p.write_text(_DB2_STUB, encoding="utf-8")
        written.append(p)

    if usage["cics"]:
        p = output_dir / "cics_interface.py"
        p.write_text(_CICS_STUB, encoding="utf-8")
        written.append(p)

    if usage["dli"]:
        p = output_dir / "dli_interface.py"
        p.write_text(_DLI_STUB, encoding="utf-8")
        written.append(p)

    if usage["mq"]:
        p = output_dir / "mq_interface.py"
        p.write_text(_MQ_STUB, encoding="utf-8")
        written.append(p)

    return written
