"""Automatic pytest test generation from translated COBOL programs.

Generates regression tests that verify:
- Program instantiation succeeds
- Data item types and initial values are correct
- Paragraph methods are callable without crashing
- DISPLAY output for simple programs matches expected patterns
"""

from __future__ import annotations

from .models import CobolProgram, DataItem, PicCategory, SoftwareMap
from .utils import _to_python_name, _to_method_name


def generate_tests(smap: SoftwareMap, module_name: str) -> str:
    """Generate a pytest test file for a translated COBOL program.

    Args:
        smap: The analyzed software map.
        module_name: The Python module name (without .py) of the translated file.

    Returns:
        Python source code for a pytest test file.
    """
    program = smap.program
    pid = program.program_id or "UNNAMED"
    class_name = _to_python_name(pid).title().replace("_", "")
    data_class = f"{class_name}Data"
    program_class = f"{class_name}Program"

    lines = [
        f'"""Auto-generated regression tests for {pid}.',
        '',
        'Generated by cobol-safe-translator test_generator.',
        f'Run: pytest {module_name}_test.py -v',
        '"""',
        '',
        'import subprocess',
        'import sys',
        'from pathlib import Path',
        '',
        'import pytest',
        '',
        '# Import the translated program',
        f'from {module_name} import {data_class}, {program_class}',
        '',
        '',
    ]

    # Test 1: Instantiation
    lines.extend([
        'class TestInstantiation:',
        '    """Verify the program can be created without errors."""',
        '',
        '    def test_data_class_instantiation(self):',
        f'        data = {data_class}()',
        '        assert data is not None',
        '',
        '    def test_program_class_instantiation(self):',
        f'        program = {program_class}()',
        '        assert program is not None',
        '        assert hasattr(program, "data")',
        '        assert hasattr(program, "run")',
        '',
        '',
    ])

    # Test 2: Data item types and initial values
    data_tests = _generate_data_tests(program, data_class)
    if data_tests:
        lines.extend([
            'class TestDataItems:',
            '    """Verify data item types and initial values."""',
            '',
        ])
        lines.extend(data_tests)
        lines.append('')

    # Test 3: Paragraph methods exist and are callable
    if program.paragraphs:
        lines.extend([
            'class TestParagraphs:',
            '    """Verify paragraph methods exist."""',
            '',
        ])
        for para in program.paragraphs:
            method = _to_method_name(para.name)
            lines.extend([
                f'    def test_{method}_exists(self):',
                f'        program = {program_class}()',
                f'        assert hasattr(program, "{method}")',
                f'        assert callable(getattr(program, "{method}"))',
                f'',
            ])
        lines.append('')

    # Test 4: Execution test (run in subprocess)
    lines.extend([
        'class TestExecution:',
        '    """Verify the program runs without crashing."""',
        '',
        '    def test_program_runs(self):',
        '        """Run the translated program in a subprocess."""',
        f'        module_path = Path(__file__).parent / "{module_name}.py"',
        '        if not module_path.exists():',
        '            pytest.skip("Translated module not found")',
        '        result = subprocess.run(',
        '            [sys.executable, str(module_path)],',
        '            capture_output=True, text=True, timeout=10,',
        '        )',
        '        # Program should not crash (exit 0 or 1 are both acceptable)',
        '        assert result.returncode in (0, 1), (',
        '            f"Program crashed with exit code {result.returncode}:\\n"',
        '            f"stderr: {result.stderr}"',
        '        )',
        '',
    ])

    # Test 5: DISPLAY output verification (if we can determine expected output)
    display_tests = _generate_display_tests(program, program_class, module_name)
    if display_tests:
        lines.extend(display_tests)

    return '\n'.join(lines)


def _flatten_items(
    items: list[DataItem], parent_has_occurs: bool = False,
) -> list[tuple[DataItem, bool]]:
    """Recursively flatten a data item tree into leaf items with OCCURS flag.

    Returns (item, in_occurs_context) tuples. in_occurs_context is True
    when the item itself or any ancestor has an OCCURS clause, meaning
    the generated field is a list rather than a scalar.
    """
    result: list[tuple[DataItem, bool]] = []
    for item in items:
        has_occurs = parent_has_occurs or bool(item.occurs)
        if item.children:
            result.extend(_flatten_items(item.children, has_occurs))
        else:
            result.append((item, has_occurs))
    return result


def _generate_data_tests(program: CobolProgram, data_class: str) -> list[str]:
    """Generate tests for data item types and initial values."""
    lines: list[str] = []
    flat = _flatten_items(program.all_data_items)

    for item, in_occurs in flat:
        if not item.pic:
            continue
        if item.name.upper() == "FILLER":
            continue
        # OCCURS items (or children of OCCURS groups) become lists; skip
        if in_occurs:
            continue

        py_name = _to_python_name(item.name)

        if item.pic.category in (PicCategory.NUMERIC, PicCategory.EDITED):
            # Check usage for float/int types
            if item.usage and item.usage.upper() in (
                "COMP-1", "COMP-2", "COMPUTATIONAL-1", "COMPUTATIONAL-2",
            ):
                lines.extend([
                    f'    def test_{py_name}_is_float(self):',
                    f'        data = {data_class}()',
                    f'        assert isinstance(data.{py_name}, float)',
                    f'',
                ])
            elif item.usage and item.usage.upper() in (
                "COMP-5", "COMPUTATIONAL-5",
            ):
                lines.extend([
                    f'    def test_{py_name}_is_int(self):',
                    f'        data = {data_class}()',
                    f'        assert isinstance(data.{py_name}, int)',
                    f'',
                ])
            else:
                lines.extend([
                    f'    def test_{py_name}_is_decimal(self):',
                    f'        from cobol_safe_translator.adapters import CobolDecimal',
                    f'        data = {data_class}()',
                    f'        assert isinstance(data.{py_name}, CobolDecimal)',
                    f'',
                ])
                if item.value:
                    lines.extend([
                        f'    def test_{py_name}_initial_value(self):',
                        f'        data = {data_class}()',
                        f'        assert data.{py_name}.value == {_safe_value(item.value)}',
                        f'',
                    ])
        else:
            lines.extend([
                f'    def test_{py_name}_is_string(self):',
                f'        from cobol_safe_translator.adapters import CobolString',
                f'        data = {data_class}()',
                f'        assert isinstance(data.{py_name}, CobolString)',
                f'',
            ])

    return lines


def _generate_display_tests(
    program: CobolProgram, program_class: str, module_name: str,
) -> list[str]:
    """Generate output verification tests for simple DISPLAY statements."""
    # Find paragraphs with DISPLAY statements containing literals
    simple_displays: list[str] = []
    for para in program.paragraphs:
        for stmt in para.statements:
            if stmt.verb == "DISPLAY":
                # Extract literal values from operands
                literals: list[str] = []
                for op in stmt.operands:
                    if (op.startswith('"') or op.startswith("'")) and len(op) >= 2:
                        literals.append(op[1:-1])
                if literals:
                    simple_displays.append(' '.join(literals))
            elif stmt.verb in ("STOP", "GOBACK"):
                break

    if not simple_displays:
        return []

    lines = [
        '',
        'class TestDisplayOutput:',
        '    """Verify DISPLAY output contains expected strings."""',
        '',
        '    def test_output_contains_expected(self):',
        '        """Check that program output includes known DISPLAY literals."""',
        f'        module_path = Path(__file__).parent / "{module_name}.py"',
        '        if not module_path.exists():',
        '            pytest.skip("Translated module not found")',
        '        result = subprocess.run(',
        '            [sys.executable, str(module_path)],',
        '            capture_output=True, text=True, timeout=10,',
        '        )',
        '        output = result.stdout',
    ]

    # Limit to first 5 to keep tests manageable
    for display in simple_displays[:5]:
        safe_display = display.replace('"', '\\"')
        lines.append(f'        assert "{safe_display}" in output')

    lines.append('')
    return lines


def _safe_value(value: str) -> str:
    """Convert a COBOL VALUE to a Python literal for assertions."""
    if value.replace('.', '').replace('-', '').replace('+', '').isdigit():
        return value
    return repr(value)
